# Site settings
title: Codivity Blog
email: 0xcodezero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All that is related to me, Ahmed Ghalab: A Muslim, Arab Egyptian Software Engineer @GIS_TIC Mekkah, working previously for @freelancing, @vimov.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://0xcodezero.github.io" # the base hostname & protocol for your site
twitter_username: iAhmedZizo
github_username:  0xcodezero

# Build settings
markdown: kramdown
